#!/bin/bash

if [[ $(pwd) != *raw.gm-lang.org ]]
then
	echo "wrong workplace"
	exit 0
fi

root=$(pwd)
git pull --rebase=false

cd $root/raw/gm
git pull --rebase=false

cd $root/pygments_gm
git pull --rebase=false


if [[ $OSTYPE == linux-gnu* ]]
then 
	sudo cp $root/raw.service /etc/systemd/system/raw.service
	sudo systemctl daemon-reload
	
	sudo systemctl restart raw
	sleep 1s
	systemctl status raw
fi